export const GAME_CATEGORIES: { value: string; label: string }[] = [
  { value: 'battle-royale', label: 'Battle Royale' },
  { value: 'sandbox', label: 'סנדבוקס' },
  { value: 'fps', label: 'ירי (FPS)' },
  { value: 'moba', label: 'MOBA' },
  { value: 'strategy', label: 'אסטרטגיה' },
  { value: 'rpg', label: 'RPG' },
  { value: 'sports', label: 'ספורט' },
  { value: 'arcade', label: 'ארקייד' },
  { value: 'puzzle', label: 'פאזל' },
  { value: 'action', label: 'אקשן' },
  { value: 'mmo', label: 'MMO' },
  { value: 'ar', label: 'מציאות רבודה' },
  { value: 'fighting', label: 'קרבות' },
  { value: 'racing', label: 'מרוצים' },
  { value: 'simulation', label: 'סימולציה' },
  { value: 'survival', label: 'הישרדות' },
  { value: 'board', label: 'משחקי לוח' },
  { value: 'casual', label: 'קז\'ואל' },
  { value: 'social', label: 'חברתי' },
];
